### ISSUE TITLE
Text Formatting in Stored Procedures is stripped by Mybatis

### ISSUE THREAD

**Issue by jeffstetson** [mybatis/migrations-maven-plugin#11]
When we run Mybatis on an mssql server, all of the formatting present in the create script in the script folder for deployment with mybaits, all the line spacing, blank lines, any meanifeul formatting is all stripped and jumbled when you view the stored procedure in the db itself.

**Comment by harawata** [comment]
I am not sure if it works or not, but try configuring ```full_line_delimiter``` or ```send_full_script``` in the environment properties file.

**Comment by hazendaz** [comment]
closing really old issue.
