### ISSUE TITLE
include plugin in migrations releases even just as a version bump

### ISSUE THREAD

**Issue by psacc** [mybatis/migrations-maven-plugin#73]
Currently the migrations plugin does not depend on the latest migrations library version. It's possible to specify the version by adding a direct dependency in the plugin section of the POM, if the library is still compatible.

But it is still conter intuitive and most users won't benefit from the latest migrations improvements when using the plugin.

Can the plugin be included in the migrations release train?

**Comment by hazendaz** [comment]
@psacc Way overdue for a release.  Can you try the latest snapshot and confirm it's working as expected?  I can push a release after confirmation.

**Comment by hazendaz** [comment]
recent release versions have since occurred, closing.  Adding direct dependency is possible as well to get newer versions as needed.
